-
  name: Copyf File to Target servers
  hosts: all
  tasks: 
    - user: 
       name : '{{ item.name}}' 
       state: present 
       uid: '{{item.uid}}'
      loop: 
       - name : joe
         uid: 1010
       - name: george
         uid: 1011
       - name: ravi
         uid: 1012
       - name: kiran
         uid: 1013
      become: yes

    - name: Copy File
      copy: 
       src: /tmp/test-file.txt
       dest: /tmp/test-file.txt       
      register: copy_res
      become: yes
     

    - name: 
      debug : 
       msg : "{{copy_res}}"
      when: copy_res is defined
