-
  name: Copyf File to Target servers
  hosts: all
  tasks: 
    - name: Copy File
      copy: 
       src: /tmp/test-file.txt
       dest: /tmp/test-file.txt       
      register: copy_res
      become: yes
     

    - name: 
      debug : 
       msg : "{{copy_res}}"
      when: copy_res is defined
    
    - user: name = '{{ item}}' state=present
      loop: 
       - joe
       - george
       - ravi
       - kiran

