- 
  name: Check Connectivity to Target Servers
  hosts: all
  vars:   
  tasks: 
   - name: Ping test
     ping: 
     register: ping_res

   - name: 
     debug : 
       msg : "{{ping_res}}"
     when: ping_res is defined  