-
  name: Copyf File to Target servers
  hosts: all
  tasks: 
    - name: Copy File
      copy: 
       src: /tmp/test-file.txt
       dest: /tmp/Copy_file.txt
       owner: root
       group: root
       mode: 0644
      register: copy_res
      become: yes
      become_user: root

    - name: 
      debug : 
       msg : "{{copy_res}}"
      when: copy_res is defined
