-
  name: Copyf File to Target servers
  hosts: all
  tasks: 
    - name: Copy File
      copy: 
       src: /tmp/test-file.txt
       dest: /tmp/
      register: copy_res

    - name: 
      debug : 
       msg : "{{copy_res}}"
      when: copy_res is defined
