  - name: Deploy a web application 
    hosts: db_and_webserver1,db_and_webserver2
    become: True
    vars:
      ansible_python_interpreter: /usr/bin/python3
    tasks: 
      - name: try ping target
        ping: 
      
      - name: yum-clean-metadata
        ansible.builtin.command: yum clean metadata
        args:
          warn: no
          
      - name: Add Epel repository
        yum_repository:
          name: epel
          description: EPEL YUM repo
          #baseurl: https://download.fedoraproject.org/pub/epel/$releasever/Everything/$basearch/
          mirrorlist: https://mirror.umd.edu/fedora/epel/8/Everything/x86_64/repodata/repomd.xml
        register: results
        
      
      - name: Install all required dependencies
        ignore_errors: yes
        yum:
          name: "{{ packages }}"
          state: present
        vars:
          packages:
            - python38 
            - python38-devel
            - python38-pip