  - name: Deploy a web application 
    hosts: db_and_webserver1,db_and_webserver2
    become: True
    vars:
      ansible_python_interpreter: /usr/bin/python3
    tasks: 
      - name: try ping target
        ping: 
      
      - name: yum-clean-metadata
        ansible.builtin.command: yum clean metadata
        args:
          warn: no

      - name: Remove Epel repository
        yum_repository:
          name: epel
          state: absent
              

      - name: Add Epel repository
        yum_repository:
          name: epel
          description: EPEL YUM repo
          baseurl: https://download.fedoraproject.org/pub/epel/7/$basearch/
          
        register: results
        
      
      - name: Install all required dependencies
        ignore_errors: yes
        become: true
        yum:
          name: "{{ packages }}"
          state: present
        vars:
          packages:
            - python38