  - name: Deploy a web application 
    hosts: db_and_webserver1,db_and_webserver2
    become: true
    vars:
      ansible_python_interpreter: /usr/bin/python3
    tasks: 
      - name: try ping target
        ping: 
      
      - name: Add repository
        ansible.builtin.yum_repository:
          name: epel-release
          description: EPEL YUM repo
          baseurl: http://download.fedoraproject.org/pub/epel
      
      