  - name: Deploy a web application 
    hosts: db_and_webserver1,db_and_webserver2
    become: true
    vars:
      ansible_python_interpreter: /usr/bin/python3
    tasks: 
      - name: try ping target
        ping: 
      
   
      
      - name: Install all required dependencies
        yum:
          name: "{{ packages }}"
          state: present
        vars:
          packages:
            - python38
            - python38-devel
            - python38-pip